// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfRv8WJGc8JdnuQZcSND1G5B5OnLH_Oqc',
    appId: '1:914875969743:web:8bcdfc58f8bfcef04347ba',
    messagingSenderId: '914875969743',
    projectId: 'atom-ai-app-f99a3',
    authDomain: 'atom-ai-app-f99a3.firebaseapp.com',
    storageBucket: 'atom-ai-app-f99a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKmvXr9TKlYosh-zGF8SkOOlnqmyJ3SDI',
    appId: '1:914875969743:android:a9fbd80555d8f4434347ba',
    messagingSenderId: '914875969743',
    projectId: 'atom-ai-app-f99a3',
    storageBucket: 'atom-ai-app-f99a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYQgNT4im1joIYWZiQHWQN2P4ZcmsH1Q',
    appId: '1:914875969743:ios:0b3d79afa81e59c64347ba',
    messagingSenderId: '914875969743',
    projectId: 'atom-ai-app-f99a3',
    storageBucket: 'atom-ai-app-f99a3.firebasestorage.app',
    iosBundleId: 'com.example.atomAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHYQgNT4im1joIYWZiQHWQN2P4ZcmsH1Q',
    appId: '1:914875969743:ios:0b3d79afa81e59c64347ba',
    messagingSenderId: '914875969743',
    projectId: 'atom-ai-app-f99a3',
    storageBucket: 'atom-ai-app-f99a3.firebasestorage.app',
    iosBundleId: 'com.example.atomAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfRv8WJGc8JdnuQZcSND1G5B5OnLH_Oqc',
    appId: '1:914875969743:web:86239f9b720348be4347ba',
    messagingSenderId: '914875969743',
    projectId: 'atom-ai-app-f99a3',
    authDomain: 'atom-ai-app-f99a3.firebaseapp.com',
    storageBucket: 'atom-ai-app-f99a3.firebasestorage.app',
  );
}
